# DoorBird
  alias: DoorBird Ring
  trigger:
    platform: event
    event_type: doorbird_front_door_button
  action:
    - service: media_player.sonos_snapshot
      data:
        entity_id: media_player.living_room, media_player.kitchen
    - service: media_player.volume_set
      data:
        entity_id: group.sound_downstairs
        volume_level: 0.4
    - service: media_player.select_source
      data:
        entity_id: group.sound_downstairs
        source: Doorbell 7
    - delay:
        seconds: 3
    - service: media_player.sonos_restore
      data:
        entity_id: media_player.living_room, media_player.kitchen