homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 50.836689
  longitude: 4.662733
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 49
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: UTC
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend


# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Add link to configurator in sidebar
panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://hassio.local:3218

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

#Slack integratie
notify:
  - name: apu
    platform: slack
    api_key: xoxp-459757368885-460934274022-460941884678-b98ad069d9fdadf2ec173430c80f6e06
    default_channel: '#general'

# DoorBird
doorbird:
  devices:
  - host: !secret doorbird_host
    username: !secret doorbird_username
    password: !secret doorbird_password
    hass_url_override: !secret doorbird_hass_url_override
    name: front_door
    monitored_conditions:
      - doorbell
camera:
  - platform: doorbird
switch:
  - platform: doorbird
    switches:
      - light_on
